# Generated by Django 3.1.1 on 2020-09-11 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hydra', 'unaccent_extension'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='nombre')),
                ('route', models.CharField(max_length=512, verbose_name='ruta')),
                ('icon_class', models.CharField(blank=True, max_length=128, null=True, verbose_name='clase css del ícono')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='última fecha de modificación')),
                ('sequence', models.PositiveSmallIntegerField(verbose_name='secuencia')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo?')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='modelo')),
                ('created_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_menus', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('modified_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updated_menus', to=settings.AUTH_USER_MODEL, verbose_name='modificado por')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submenus', to='hydra.menu', verbose_name='menú padre')),
            ],
            options={
                'ordering': ('route', 'sequence'),
            },
        ),
    ]
